version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tienda_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: HOLA123
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=tienda_db
      - SQL_USER=postgres
      - SQL_PASSWORD=HOLA123
      - SQL_HOST=db
      - SQL_PORT=5432
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 0.0.0.0