# Generated by Django 6.0.4 on 2026-04-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0002_orden_usuario_direccion_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='libro',
        ),
    ]
